<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StarsandIsland.SeedSeasonDisplay</AssemblyName>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <StarsandIslandDir Condition="'$(StarsandIslandDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\StarsandIsland</StarsandIslandDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(StarsandIslandDir)\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(StarsandIslandDir)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameFramework">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\GameFramework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameWorld">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\GameWorld.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UI">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(StarsandIslandDir)\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(StarsandIslandDir)\BepInEx\interop\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\spring.png" LogicalName="StarsandIsland.SeedSeasonDisplay.Assets.spring.png" />
    <EmbeddedResource Include="Assets\summer.png" LogicalName="StarsandIsland.SeedSeasonDisplay.Assets.summer.png" />
    <EmbeddedResource Include="Assets\fall.png" LogicalName="StarsandIsland.SeedSeasonDisplay.Assets.fall.png" />
    <EmbeddedResource Include="Assets\winter.png" LogicalName="StarsandIsland.SeedSeasonDisplay.Assets.winter.png" />
  </ItemGroup>
</Project>
